# Generated by Django 2.1.5 on 2020-10-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer_prod_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='prod_name',
            new_name='product_name',
        ),
    ]
